"""remaining data model tables

Every table docs/02-DATA-MODEL.md defines that hadn't yet landed (`tenants`/`users`/`uploads`/
`analyses` shipped in `b67faee96cf5`, `events` in `93944a5223d9`, `dead_letters` in
`3ecd8a2dc9bd`): detection (`signals`), graph & incidents (`entities`, `entity_edges`,
`incidents`), triage & response (`triage_verdicts`, `response_plans`), the enforcement plane
(`enforcement_state`, `enforcement_journal`), learning (`analyst_feedback`, `detector_stats`,
`model_versions`), and ops/eval (`tier2_signatures`, `eval_runs`). See `app/models/` for the
matching ORM models and their per-table docstrings.

Table creation order below is a topological sort on FK dependencies (autogenerate's own
ordering, left as-is): `entities` before `entity_edges` (which references it), `incidents`
before `triage_verdicts`/`response_plans` (which reference it), `response_plans` before
`enforcement_journal` (which references it), `triage_verdicts` before `analyst_feedback` (which
references it). `downgrade()` mirrors this in reverse, children before parents.

Two things matter more than the rest:

* `incidents.embedding VECTOR(1024)` backs `ix_incidents_embedding_hnsw`, an
  `hnsw (embedding vector_cosine_ops)` index — pgvector's approximate nearest-neighbor index,
  used for recurrence search. `tier2_signatures.embedding` is also `VECTOR(1024)` but docs/02
  specifies no index on it, so none is created.
* `tenant_id` on `signals`/`incidents`/`enforcement_state`/`detector_stats` overrides
  `TenantScopedMixin`'s default column (no FK, no bare index) exactly like `events` already
  does — matching docs/02's literal SQL, which never gives these high-volume/detection tables
  a `REFERENCES tenants(id)` FK. Every other new table here either has no `tenant_id` at all
  (isolation is transitive through an `analysis_id`/`incident_id`/... FK to a tenant-scoped
  table) or, for `tier2_signatures`, deliberately carries `tenant_hash` instead — an HMAC under
  a cross-tenant-shared salt (docs/06), not a `tenant_id`, so cross-tenant indicator overlap is
  detectable without exposing any tenant's raw data to another.

Revision ID: 62f176de175c
Revises: 3ecd8a2dc9bd
Create Date: 2026-08-14 22:45:00.202676
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "62f176de175c"
down_revision: str | None = "3ecd8a2dc9bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detector_stats",
        sa.Column("detector_key", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("true_positives", sa.Integer(), server_default="0", nullable=False),
        sa.Column("false_positives", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fusion_weight", sa.REAL(), server_default="1.0", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("detector_key"),
    )
    op.create_table(
        "enforcement_state",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=False),
        sa.Column("resource_id", sa.Text(), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "resource_type",
            "resource_id",
            name="uq_enforcement_state_tenant_id_resource_type_resource_id",
        ),
    )
    op.create_table(
        "eval_runs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("git_sha", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("model_key", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("artifact_ref", sa.Text(), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("eval_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("promoted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_key", "version", name="uq_model_versions_model_key_version"),
    )
    op.create_table(
        "tier2_signatures",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_hash", sa.Text(), nullable=False),
        sa.Column("incident_type", sa.Text(), nullable=False),
        sa.Column("mitre_techniques", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("source_types", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("confidence", sa.REAL(), nullable=False),
        sa.Column("indicator_hashes", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("risk_score", sa.REAL(), server_default="0", nullable=False),
        sa.Column(
            "attrs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "analysis_id", "type", "value", name="uq_entities_analysis_id_type_value"
        ),
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("fused_score", sa.REAL(), nullable=False),
        sa.Column("entity_ids", sa.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("signal_ids", sa.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("recurrence_of", sa.Uuid(), nullable=True),
        sa.Column("recurrence_similarity", sa.REAL(), nullable=True),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["recurrence_of"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_incidents_embedding_hnsw",
        "incidents",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("detector_key", sa.Text(), nullable=False),
        sa.Column("detector_layer", sa.Text(), nullable=False),
        sa.Column("raw_score", sa.REAL(), nullable=False),
        sa.Column("confidence", sa.REAL(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_value", sa.Text(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mitre_technique", sa.Text(), nullable=True),
        sa.Column("evidence_event_ids", sa.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_signals_analysis_id_confidence",
        "signals",
        ["analysis_id", sa.literal_column("confidence DESC")],
        unique=False,
    )
    op.create_table(
        "entity_edges",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("src_entity_id", sa.BigInteger(), nullable=False),
        sa.Column("dst_entity_id", sa.BigInteger(), nullable=False),
        sa.Column("relation", sa.Text(), nullable=False),
        sa.Column("weight", sa.REAL(), server_default="1", nullable=False),
        sa.Column("event_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["dst_entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["src_entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "response_plans",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verification", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending_approval", nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "execution_log",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("outcome_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "triage_verdicts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("disposition", sa.Text(), nullable=False),
        sa.Column("confidence", sa.REAL(), nullable=False),
        sa.Column("llm_severity_opinion", sa.Text(), nullable=True),
        sa.Column("mitre_techniques", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("narrative", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contradicting_evidence", sa.Text(), nullable=True),
        sa.Column("recommended_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tool_trace", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("citation_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "invalid_citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analyst_feedback",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("verdict_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("agrees", sa.Boolean(), nullable=False),
        sa.Column("corrected_disposition", sa.Text(), nullable=True),
        sa.Column("corrected_technique", sa.Text(), nullable=True),
        sa.Column("dismissal_reason", sa.Text(), nullable=True),
        sa.Column(
            "mark_benign_baseline", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verdict_id"],
            ["triage_verdicts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "enforcement_journal",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Text(), nullable=False),
        sa.Column("before_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("precondition_failure", sa.Text(), nullable=True),
        sa.Column(
            "executed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["response_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("enforcement_journal")
    op.drop_table("analyst_feedback")
    op.drop_table("triage_verdicts")
    op.drop_table("response_plans")
    op.drop_table("entity_edges")
    op.drop_index("ix_signals_analysis_id_confidence", table_name="signals")
    op.drop_table("signals")
    op.drop_index(
        "ix_incidents_embedding_hnsw",
        table_name="incidents",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("incidents")
    op.drop_table("entities")
    op.drop_table("tier2_signatures")
    op.drop_table("model_versions")
    op.drop_table("eval_runs")
    op.drop_table("enforcement_state")
    op.drop_table("detector_stats")
    # ### end Alembic commands ###
