import type { ModelComparisonTable } from "./api/types";

/**
 * `GET /api/models` (the live comparison-tables endpoint docs/09 documents) is explicitly
 * M16's job and is not implemented in this checkout (`backend/app/api/models.py`'s own module
 * docstring says so). Rather than leave `/models` with nothing but an empty state — which
 * would defeat the entire point of this page (docs/10: "This page exists so the benchmarking
 * discipline is visible rather than buried in a README") — this is the real L3 benchmark
 * table from `backend/evals/results.md` (generated by `python -m app.detection.ml.train` +
 * `.evaluate`, real data, not hand-edited per that file's own header), transcribed verbatim
 * and clearly labelled on the page as a static, checked-in report rather than a live call.
 * Swap this whole module out the day `GET /api/models` exists.
 */
export const STATIC_RESULTS_SOURCE = "backend/evals/results.md (M8 run, generated by app.detection.ml.train + .evaluate)";

export const L3_COMPARISON: ModelComparisonTable = {
  layer: "L3 unsupervised (entity-window ML)",
  metric_note:
    "Winner is the pre-registered rule (highest mean F1 at the fixed 99.5th-percentile threshold) — but read the caveat below before trusting it as \"best model.\"",
  contenders: [
    {
      model_key: "ml.iforest",
      mean_f1: 0.125,
      mean_auc_pr: 0.173,
      mean_recall: 0.125,
      mean_precision: 0.125,
      scenarios_detected: 1,
      scenarios_total: 8,
      is_winner: true,
    },
    {
      model_key: "ml.mahalanobis",
      mean_f1: 0.007,
      mean_auc_pr: 0.059,
      mean_recall: 0.042,
      mean_precision: 0.004,
      scenarios_detected: 1,
      scenarios_total: 8,
      is_winner: false,
    },
    {
      model_key: "ml.autoencoder",
      mean_f1: 0.029,
      mean_auc_pr: 0.292,
      mean_recall: 0.632,
      mean_precision: 0.015,
      scenarios_detected: 6,
      scenarios_total: 8,
      is_winner: false,
    },
  ],
};

export const L3_READING_NOTE =
  "ml.iforest's win is driven almost entirely by one perfect hit on data_exfiltration and total " +
  "silence (0 recall) on the other seven scenarios. ml.autoencoder has ~5x the AUC-PR (0.292 vs " +
  "0.173) and detects six of eight scenarios instead of one, at the cost of a much higher false-" +
  "positive rate (3.4% vs 0.0%). Scenario 8 (low-and-slow exfil) — the scenario built specifically " +
  "to justify the autoencoder's slot — is detected by none of the three models (recall 0.0 across " +
  "the board). The honest conclusion is not \"ship Isolation Forest\": neither model is shippable " +
  "as-is, and this benchmark should be re-run after M10's per-detector isotonic calibration.";

export const FALSE_POSITIVE_RATES: Array<{ model_key: string; fp_all_benign: number; fp_benign_but_weird: number }> = [
  { model_key: "ml.iforest", fp_all_benign: 0.0, fp_benign_but_weird: 0.0 },
  { model_key: "ml.mahalanobis", fp_all_benign: 0.006, fp_benign_but_weird: 0.002 },
  { model_key: "ml.autoencoder", fp_all_benign: 0.034, fp_benign_but_weird: 0.026 },
];

export const L4_RETROSPECTIVE = {
  note:
    "L4 sequence models (Markov, LogBERT) were built and benchmarked under the old multi-source " +
    "design, then cut when the system moved to ZScaler-only — their justification was identity-log " +
    "ordering, which no longer exists. Kept here as the fossil record docs/13 describes, not a live " +
    "contender.",
  rows: [
    { model_key: "markov", pooled_f1: 0.529, winner: true },
    { model_key: "logbert", pooled_f1: 0.097, winner: false },
  ],
};

/**
 * docs/v2_migration change 27, `/learning` section 2: "Hypothesis outcomes — the table
 * from `docs/12`, with predictions recorded before the run." Transcribed verbatim from
 * `backend/evals/results.md`'s "Pre-registered predictions — measured against real
 * numbers" section, same static/checked-in treatment as `L3_COMPARISON` above (real
 * data, not fabricated — CLAUDE.md's "losing is a valid, reportable outcome" applies
 * here as much as to the comparison table: two of the three predictions came back
 * FALSIFIED, and that is reported plainly, not smoothed over).
 *
 * The models these predictions name (`ml.autoencoder` in particular) predate
 * docs/v2_migration change 19's autoencoder removal — this table is the historical
 * record of what was predicted and measured *at the time*, not a claim about the
 * current model roster. `/learning`'s Model performance section carries the same
 * caveat about the live roster having moved on since this run.
 */
export interface HypothesisOutcome {
  n: number;
  prediction: string;
  outcome: "confirmed" | "falsified";
  measured: string;
}

export const HYPOTHESIS_OUTCOMES: HypothesisOutcome[] = [
  {
    n: 1,
    prediction: "Scenario 4 (low-and-slow exfil): autoencoder detects it, ECOD does not",
    outcome: "confirmed",
    measured:
      "ml.autoencoder recall 0.048 (detected); ml.ecod recall 0.000 (not detected). Only " +
      "ml.mahalanobis and ml.autoencoder detected it at all.",
  },
  {
    n: 2,
    prediction: "Scenario 5 (peer-group deviation): LOF detects it, the four global models do not",
    outcome: "falsified",
    measured:
      "LOF (ml.peer_group) detected it (recall 0.026) — but so did ml.mahalanobis (0.453), " +
      "ml.ecod (0.009), and ml.autoencoder (0.043). Only ml.iforest stayed silent.",
  },
  {
    n: 3,
    prediction: "Scenario 6 (seasonal deviation): STL detects it, none of the five L3 models do",
    outcome: "falsified",
    measured:
      "STL (signal.stl_residual) did not detect it — 0 of 36 malicious lines recovered when " +
      "scored in isolation. Two L3 models (ml.mahalanobis 0.778 recall, ml.peer_group 0.028) " +
      "did detect it via the entity-window snapshot.",
  },
];
