import type { ModelComparisonTable } from "./api/types";

/**
 * `GET /api/models` (the live comparison-tables endpoint docs/09 documents) is explicitly
 * M16's job and is not implemented in this checkout (`backend/app/api/models.py`'s own module
 * docstring says so). Rather than leave `/models` with nothing but an empty state — which
 * would defeat the entire point of this page (docs/10: "This page exists so the benchmarking
 * discipline is visible rather than buried in a README") — this is the real L3 benchmark
 * table from `backend/evals/results.md` (generated by `python -m app.detection.ml.train` +
 * `.evaluate`, real data, not hand-edited per that file's own header), transcribed verbatim
 * and clearly labelled on the page as a static, checked-in report rather than a live call.
 * Swap this whole module out the day `GET /api/models` exists.
 */
export const STATIC_RESULTS_SOURCE = "backend/evals/results.md (M8 run, generated by app.detection.ml.train + .evaluate)";

export const L3_COMPARISON: ModelComparisonTable = {
  layer: "L3 unsupervised (entity-window ML)",
  metric_note:
    "Winner is the pre-registered rule (highest mean F1 at the fixed 99.5th-percentile threshold) — but read the caveat below before trusting it as \"best model.\"",
  contenders: [
    {
      model_key: "ml.iforest",
      mean_f1: 0.125,
      mean_auc_pr: 0.173,
      mean_recall: 0.125,
      mean_precision: 0.125,
      scenarios_detected: 1,
      scenarios_total: 8,
      is_winner: true,
    },
    {
      model_key: "ml.mahalanobis",
      mean_f1: 0.007,
      mean_auc_pr: 0.059,
      mean_recall: 0.042,
      mean_precision: 0.004,
      scenarios_detected: 1,
      scenarios_total: 8,
      is_winner: false,
    },
    {
      model_key: "ml.autoencoder",
      mean_f1: 0.029,
      mean_auc_pr: 0.292,
      mean_recall: 0.632,
      mean_precision: 0.015,
      scenarios_detected: 6,
      scenarios_total: 8,
      is_winner: false,
    },
  ],
};

export const L3_READING_NOTE =
  "ml.iforest's win is driven almost entirely by one perfect hit on data_exfiltration and total " +
  "silence (0 recall) on the other seven scenarios. ml.autoencoder has ~5x the AUC-PR (0.292 vs " +
  "0.173) and detects six of eight scenarios instead of one, at the cost of a much higher false-" +
  "positive rate (3.4% vs 0.0%). Scenario 8 (low-and-slow exfil) — the scenario built specifically " +
  "to justify the autoencoder's slot — is detected by none of the three models (recall 0.0 across " +
  "the board). The honest conclusion is not \"ship Isolation Forest\": neither model is shippable " +
  "as-is, and this benchmark should be re-run after M10's per-detector isotonic calibration.";

export const FALSE_POSITIVE_RATES: Array<{ model_key: string; fp_all_benign: number; fp_benign_but_weird: number }> = [
  { model_key: "ml.iforest", fp_all_benign: 0.0, fp_benign_but_weird: 0.0 },
  { model_key: "ml.mahalanobis", fp_all_benign: 0.006, fp_benign_but_weird: 0.002 },
  { model_key: "ml.autoencoder", fp_all_benign: 0.034, fp_benign_but_weird: 0.026 },
];

export const L4_RETROSPECTIVE = {
  note:
    "L4 sequence models (Markov, LogBERT) were built and benchmarked under the old multi-source " +
    "design, then cut when the system moved to ZScaler-only — their justification was identity-log " +
    "ordering, which no longer exists. Kept here as the fossil record docs/13 describes, not a live " +
    "contender.",
  rows: [
    { model_key: "markov", pooled_f1: 0.529, winner: true },
    { model_key: "logbert", pooled_f1: 0.097, winner: false },
  ],
};
